version: "3.7"

services:

  php-apache:
    image: webdevops/php-apache
    links:
      - "mariadb"
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PHP_DISPLAY_ERRORS=On
    volumes:
      - "./:/app:z"

    depends_on:
      - mariadb
      - phpmyadmin

  mariadb:
    image: mariadb:10.4
    ports:
      - 3306:3306
    volumes:
      - dashboard_project-data:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - "mariadb"
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=mariadb
    depends_on:
      - mariadb

volumes:
  dashboard_project-data: