version: "3.7"

services:

  php-apache:
    image: webdevops/php-apache
    container_name: dashboard-srv
    links:
      - "mariadb"
    ports:
      - 8080:80
    environment:
      - PHP_DISPLAY_ERRORS=On
    volumes:
      - "./:/app:z"
    depends_on:
      - mariadb


  mariadb:
    image: mariadb:10.4
    container_name: dashboard-db
    ports:
      - 3306:3306
    volumes:
      - dashboard_project-data:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
    restart: unless-stopped


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dashboard-pma
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=mariadb
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  dashboard_project-data: